/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminAccessRouteImport } from './routes/admin.access'
import { Route as AdminDomainsRouteImport } from './routes/admin.domains'
import { Route as AdminLinksRouteImport } from './routes/admin.links'
import { Route as AdminUserRouteImport } from './routes/admin.user'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminAccessInvitesRouteImport } from './routes/admin.access.invites'
import { Route as AdminAccessMcpRouteImport } from './routes/admin.access.mcp'
import { Route as AdminAccessRolesRouteImport } from './routes/admin.access.roles'
import { Route as AdminAccessUsersRouteImport } from './routes/admin.access.users'
import { Route as AdminDomainsNewRouteImport } from './routes/admin.domains.new'
import { Route as AdminInviteTokenRouteImport } from './routes/admin.invite.$token'
import { Route as AdminInvitesNewRouteImport } from './routes/admin.invites.new'
import { Route as AdminLinksIdRouteImport } from './routes/admin.links.$id'
import { Route as AdminLinksNewRouteImport } from './routes/admin.links.new'
import { Route as AdminMcpConsentRouteImport } from './routes/admin.mcp.consent'
import { Route as AdminRolesNewRouteImport } from './routes/admin.roles.new'
import { Route as AdminUserApiKeysRouteImport } from './routes/admin.user.api-keys'
import { Route as AdminUserMcpRouteImport } from './routes/admin.user.mcp'
import { Route as AdminUserProfileRouteImport } from './routes/admin.user.profile'
import { Route as AdminUserSessionsRouteImport } from './routes/admin.user.sessions'
import { Route as AdminAccessRolesIdRouteImport } from './routes/admin.access.roles.$id'
import { Route as AdminAccessUsersIdRouteImport } from './routes/admin.access.users.$id'
import { Route as AdminDomainsIdEditRouteImport } from './routes/admin.domains.$id.edit'
import { Route as AdminInvitesIdEditRouteImport } from './routes/admin.invites.$id.edit'
import { Route as AdminLinksIdEditRouteImport } from './routes/admin.links.$id.edit'
import { Route as AdminRolesIdEditRouteImport } from './routes/admin.roles.$id.edit'
import { Route as AdminAccessUsersIdEditRouteImport } from './routes/admin.access.users.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDomainsRoute = AdminDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUserRoute = AdminUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessInvitesRoute = AdminAccessInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AdminAccessRoute,
} as any)
const AdminAccessMcpRoute = AdminAccessMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AdminAccessRoute,
} as any)
const AdminAccessRolesRoute = AdminAccessRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminAccessRoute,
} as any)
const AdminAccessUsersRoute = AdminAccessUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAccessRoute,
} as any)
const AdminDomainsNewRoute = AdminDomainsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminDomainsRoute,
} as any)
const AdminInviteTokenRoute = AdminInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitesNewRoute = AdminInvitesNewRouteImport.update({
  id: '/invites/new',
  path: '/invites/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinksIdRoute = AdminLinksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminLinksRoute,
} as any)
const AdminLinksNewRoute = AdminLinksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminLinksRoute,
} as any)
const AdminMcpConsentRoute = AdminMcpConsentRouteImport.update({
  id: '/mcp/consent',
  path: '/mcp/consent',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesNewRoute = AdminRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUserApiKeysRoute = AdminUserApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminUserRoute,
} as any)
const AdminUserMcpRoute = AdminUserMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AdminUserRoute,
} as any)
const AdminUserProfileRoute = AdminUserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminUserRoute,
} as any)
const AdminUserSessionsRoute = AdminUserSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminUserRoute,
} as any)
const AdminAccessRolesIdRoute = AdminAccessRolesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAccessRolesRoute,
} as any)
const AdminAccessUsersIdRoute = AdminAccessUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAccessUsersRoute,
} as any)
const AdminDomainsIdEditRoute = AdminDomainsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminDomainsRoute,
} as any)
const AdminInvitesIdEditRoute = AdminInvitesIdEditRouteImport.update({
  id: '/invites/$id/edit',
  path: '/invites/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinksIdEditRoute = AdminLinksIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminLinksIdRoute,
} as any)
const AdminRolesIdEditRoute = AdminRolesIdEditRouteImport.update({
  id: '/roles/$id/edit',
  path: '/roles/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessUsersIdEditRoute = AdminAccessUsersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminAccessUsersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/access': typeof AdminAccessRouteWithChildren
  '/admin/domains': typeof AdminDomainsRouteWithChildren
  '/admin/links': typeof AdminLinksRouteWithChildren
  '/admin/user': typeof AdminUserRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/access/invites': typeof AdminAccessInvitesRoute
  '/admin/access/mcp': typeof AdminAccessMcpRoute
  '/admin/access/roles': typeof AdminAccessRolesRouteWithChildren
  '/admin/access/users': typeof AdminAccessUsersRouteWithChildren
  '/admin/domains/new': typeof AdminDomainsNewRoute
  '/admin/invite/$token': typeof AdminInviteTokenRoute
  '/admin/invites/new': typeof AdminInvitesNewRoute
  '/admin/links/$id': typeof AdminLinksIdRouteWithChildren
  '/admin/links/new': typeof AdminLinksNewRoute
  '/admin/mcp/consent': typeof AdminMcpConsentRoute
  '/admin/roles/new': typeof AdminRolesNewRoute
  '/admin/user/api-keys': typeof AdminUserApiKeysRoute
  '/admin/user/mcp': typeof AdminUserMcpRoute
  '/admin/user/profile': typeof AdminUserProfileRoute
  '/admin/user/sessions': typeof AdminUserSessionsRoute
  '/admin/access/roles/$id': typeof AdminAccessRolesIdRoute
  '/admin/access/users/$id': typeof AdminAccessUsersIdRouteWithChildren
  '/admin/domains/$id/edit': typeof AdminDomainsIdEditRoute
  '/admin/invites/$id/edit': typeof AdminInvitesIdEditRoute
  '/admin/links/$id/edit': typeof AdminLinksIdEditRoute
  '/admin/roles/$id/edit': typeof AdminRolesIdEditRoute
  '/admin/access/users/$id/edit': typeof AdminAccessUsersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/access': typeof AdminAccessRouteWithChildren
  '/admin/domains': typeof AdminDomainsRouteWithChildren
  '/admin/links': typeof AdminLinksRouteWithChildren
  '/admin/user': typeof AdminUserRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/access/invites': typeof AdminAccessInvitesRoute
  '/admin/access/mcp': typeof AdminAccessMcpRoute
  '/admin/access/roles': typeof AdminAccessRolesRouteWithChildren
  '/admin/access/users': typeof AdminAccessUsersRouteWithChildren
  '/admin/domains/new': typeof AdminDomainsNewRoute
  '/admin/invite/$token': typeof AdminInviteTokenRoute
  '/admin/invites/new': typeof AdminInvitesNewRoute
  '/admin/links/$id': typeof AdminLinksIdRouteWithChildren
  '/admin/links/new': typeof AdminLinksNewRoute
  '/admin/mcp/consent': typeof AdminMcpConsentRoute
  '/admin/roles/new': typeof AdminRolesNewRoute
  '/admin/user/api-keys': typeof AdminUserApiKeysRoute
  '/admin/user/mcp': typeof AdminUserMcpRoute
  '/admin/user/profile': typeof AdminUserProfileRoute
  '/admin/user/sessions': typeof AdminUserSessionsRoute
  '/admin/access/roles/$id': typeof AdminAccessRolesIdRoute
  '/admin/access/users/$id': typeof AdminAccessUsersIdRouteWithChildren
  '/admin/domains/$id/edit': typeof AdminDomainsIdEditRoute
  '/admin/invites/$id/edit': typeof AdminInvitesIdEditRoute
  '/admin/links/$id/edit': typeof AdminLinksIdEditRoute
  '/admin/roles/$id/edit': typeof AdminRolesIdEditRoute
  '/admin/access/users/$id/edit': typeof AdminAccessUsersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/access': typeof AdminAccessRouteWithChildren
  '/admin/domains': typeof AdminDomainsRouteWithChildren
  '/admin/links': typeof AdminLinksRouteWithChildren
  '/admin/user': typeof AdminUserRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/access/invites': typeof AdminAccessInvitesRoute
  '/admin/access/mcp': typeof AdminAccessMcpRoute
  '/admin/access/roles': typeof AdminAccessRolesRouteWithChildren
  '/admin/access/users': typeof AdminAccessUsersRouteWithChildren
  '/admin/domains/new': typeof AdminDomainsNewRoute
  '/admin/invite/$token': typeof AdminInviteTokenRoute
  '/admin/invites/new': typeof AdminInvitesNewRoute
  '/admin/links/$id': typeof AdminLinksIdRouteWithChildren
  '/admin/links/new': typeof AdminLinksNewRoute
  '/admin/mcp/consent': typeof AdminMcpConsentRoute
  '/admin/roles/new': typeof AdminRolesNewRoute
  '/admin/user/api-keys': typeof AdminUserApiKeysRoute
  '/admin/user/mcp': typeof AdminUserMcpRoute
  '/admin/user/profile': typeof AdminUserProfileRoute
  '/admin/user/sessions': typeof AdminUserSessionsRoute
  '/admin/access/roles/$id': typeof AdminAccessRolesIdRoute
  '/admin/access/users/$id': typeof AdminAccessUsersIdRouteWithChildren
  '/admin/domains/$id/edit': typeof AdminDomainsIdEditRoute
  '/admin/invites/$id/edit': typeof AdminInvitesIdEditRoute
  '/admin/links/$id/edit': typeof AdminLinksIdEditRoute
  '/admin/roles/$id/edit': typeof AdminRolesIdEditRoute
  '/admin/access/users/$id/edit': typeof AdminAccessUsersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/access'
    | '/admin/domains'
    | '/admin/links'
    | '/admin/user'
    | '/admin/users'
    | '/admin/access/invites'
    | '/admin/access/mcp'
    | '/admin/access/roles'
    | '/admin/access/users'
    | '/admin/domains/new'
    | '/admin/invite/$token'
    | '/admin/invites/new'
    | '/admin/links/$id'
    | '/admin/links/new'
    | '/admin/mcp/consent'
    | '/admin/roles/new'
    | '/admin/user/api-keys'
    | '/admin/user/mcp'
    | '/admin/user/profile'
    | '/admin/user/sessions'
    | '/admin/access/roles/$id'
    | '/admin/access/users/$id'
    | '/admin/domains/$id/edit'
    | '/admin/invites/$id/edit'
    | '/admin/links/$id/edit'
    | '/admin/roles/$id/edit'
    | '/admin/access/users/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/access'
    | '/admin/domains'
    | '/admin/links'
    | '/admin/user'
    | '/admin/users'
    | '/admin/access/invites'
    | '/admin/access/mcp'
    | '/admin/access/roles'
    | '/admin/access/users'
    | '/admin/domains/new'
    | '/admin/invite/$token'
    | '/admin/invites/new'
    | '/admin/links/$id'
    | '/admin/links/new'
    | '/admin/mcp/consent'
    | '/admin/roles/new'
    | '/admin/user/api-keys'
    | '/admin/user/mcp'
    | '/admin/user/profile'
    | '/admin/user/sessions'
    | '/admin/access/roles/$id'
    | '/admin/access/users/$id'
    | '/admin/domains/$id/edit'
    | '/admin/invites/$id/edit'
    | '/admin/links/$id/edit'
    | '/admin/roles/$id/edit'
    | '/admin/access/users/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/access'
    | '/admin/domains'
    | '/admin/links'
    | '/admin/user'
    | '/admin/users'
    | '/admin/access/invites'
    | '/admin/access/mcp'
    | '/admin/access/roles'
    | '/admin/access/users'
    | '/admin/domains/new'
    | '/admin/invite/$token'
    | '/admin/invites/new'
    | '/admin/links/$id'
    | '/admin/links/new'
    | '/admin/mcp/consent'
    | '/admin/roles/new'
    | '/admin/user/api-keys'
    | '/admin/user/mcp'
    | '/admin/user/profile'
    | '/admin/user/sessions'
    | '/admin/access/roles/$id'
    | '/admin/access/users/$id'
    | '/admin/domains/$id/edit'
    | '/admin/invites/$id/edit'
    | '/admin/links/$id/edit'
    | '/admin/roles/$id/edit'
    | '/admin/access/users/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/domains': {
      id: '/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AdminDomainsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/user': {
      id: '/admin/user'
      path: '/user'
      fullPath: '/admin/user'
      preLoaderRoute: typeof AdminUserRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access/invites': {
      id: '/admin/access/invites'
      path: '/invites'
      fullPath: '/admin/access/invites'
      preLoaderRoute: typeof AdminAccessInvitesRouteImport
      parentRoute: typeof AdminAccessRoute
    }
    '/admin/access/mcp': {
      id: '/admin/access/mcp'
      path: '/mcp'
      fullPath: '/admin/access/mcp'
      preLoaderRoute: typeof AdminAccessMcpRouteImport
      parentRoute: typeof AdminAccessRoute
    }
    '/admin/access/roles': {
      id: '/admin/access/roles'
      path: '/roles'
      fullPath: '/admin/access/roles'
      preLoaderRoute: typeof AdminAccessRolesRouteImport
      parentRoute: typeof AdminAccessRoute
    }
    '/admin/access/users': {
      id: '/admin/access/users'
      path: '/users'
      fullPath: '/admin/access/users'
      preLoaderRoute: typeof AdminAccessUsersRouteImport
      parentRoute: typeof AdminAccessRoute
    }
    '/admin/domains/new': {
      id: '/admin/domains/new'
      path: '/new'
      fullPath: '/admin/domains/new'
      preLoaderRoute: typeof AdminDomainsNewRouteImport
      parentRoute: typeof AdminDomainsRoute
    }
    '/admin/invite/$token': {
      id: '/admin/invite/$token'
      path: '/invite/$token'
      fullPath: '/admin/invite/$token'
      preLoaderRoute: typeof AdminInviteTokenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invites/new': {
      id: '/admin/invites/new'
      path: '/invites/new'
      fullPath: '/admin/invites/new'
      preLoaderRoute: typeof AdminInvitesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/links/$id': {
      id: '/admin/links/$id'
      path: '/$id'
      fullPath: '/admin/links/$id'
      preLoaderRoute: typeof AdminLinksIdRouteImport
      parentRoute: typeof AdminLinksRoute
    }
    '/admin/links/new': {
      id: '/admin/links/new'
      path: '/new'
      fullPath: '/admin/links/new'
      preLoaderRoute: typeof AdminLinksNewRouteImport
      parentRoute: typeof AdminLinksRoute
    }
    '/admin/mcp/consent': {
      id: '/admin/mcp/consent'
      path: '/mcp/consent'
      fullPath: '/admin/mcp/consent'
      preLoaderRoute: typeof AdminMcpConsentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles/new': {
      id: '/admin/roles/new'
      path: '/roles/new'
      fullPath: '/admin/roles/new'
      preLoaderRoute: typeof AdminRolesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/user/api-keys': {
      id: '/admin/user/api-keys'
      path: '/api-keys'
      fullPath: '/admin/user/api-keys'
      preLoaderRoute: typeof AdminUserApiKeysRouteImport
      parentRoute: typeof AdminUserRoute
    }
    '/admin/user/mcp': {
      id: '/admin/user/mcp'
      path: '/mcp'
      fullPath: '/admin/user/mcp'
      preLoaderRoute: typeof AdminUserMcpRouteImport
      parentRoute: typeof AdminUserRoute
    }
    '/admin/user/profile': {
      id: '/admin/user/profile'
      path: '/profile'
      fullPath: '/admin/user/profile'
      preLoaderRoute: typeof AdminUserProfileRouteImport
      parentRoute: typeof AdminUserRoute
    }
    '/admin/user/sessions': {
      id: '/admin/user/sessions'
      path: '/sessions'
      fullPath: '/admin/user/sessions'
      preLoaderRoute: typeof AdminUserSessionsRouteImport
      parentRoute: typeof AdminUserRoute
    }
    '/admin/access/roles/$id': {
      id: '/admin/access/roles/$id'
      path: '/$id'
      fullPath: '/admin/access/roles/$id'
      preLoaderRoute: typeof AdminAccessRolesIdRouteImport
      parentRoute: typeof AdminAccessRolesRoute
    }
    '/admin/access/users/$id': {
      id: '/admin/access/users/$id'
      path: '/$id'
      fullPath: '/admin/access/users/$id'
      preLoaderRoute: typeof AdminAccessUsersIdRouteImport
      parentRoute: typeof AdminAccessUsersRoute
    }
    '/admin/domains/$id/edit': {
      id: '/admin/domains/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/domains/$id/edit'
      preLoaderRoute: typeof AdminDomainsIdEditRouteImport
      parentRoute: typeof AdminDomainsRoute
    }
    '/admin/invites/$id/edit': {
      id: '/admin/invites/$id/edit'
      path: '/invites/$id/edit'
      fullPath: '/admin/invites/$id/edit'
      preLoaderRoute: typeof AdminInvitesIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/links/$id/edit': {
      id: '/admin/links/$id/edit'
      path: '/edit'
      fullPath: '/admin/links/$id/edit'
      preLoaderRoute: typeof AdminLinksIdEditRouteImport
      parentRoute: typeof AdminLinksIdRoute
    }
    '/admin/roles/$id/edit': {
      id: '/admin/roles/$id/edit'
      path: '/roles/$id/edit'
      fullPath: '/admin/roles/$id/edit'
      preLoaderRoute: typeof AdminRolesIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access/users/$id/edit': {
      id: '/admin/access/users/$id/edit'
      path: '/edit'
      fullPath: '/admin/access/users/$id/edit'
      preLoaderRoute: typeof AdminAccessUsersIdEditRouteImport
      parentRoute: typeof AdminAccessUsersIdRoute
    }
  }
}

interface AdminAccessRolesRouteChildren {
  AdminAccessRolesIdRoute: typeof AdminAccessRolesIdRoute
}

const AdminAccessRolesRouteChildren: AdminAccessRolesRouteChildren = {
  AdminAccessRolesIdRoute: AdminAccessRolesIdRoute,
}

const AdminAccessRolesRouteWithChildren =
  AdminAccessRolesRoute._addFileChildren(AdminAccessRolesRouteChildren)

interface AdminAccessUsersIdRouteChildren {
  AdminAccessUsersIdEditRoute: typeof AdminAccessUsersIdEditRoute
}

const AdminAccessUsersIdRouteChildren: AdminAccessUsersIdRouteChildren = {
  AdminAccessUsersIdEditRoute: AdminAccessUsersIdEditRoute,
}

const AdminAccessUsersIdRouteWithChildren =
  AdminAccessUsersIdRoute._addFileChildren(AdminAccessUsersIdRouteChildren)

interface AdminAccessUsersRouteChildren {
  AdminAccessUsersIdRoute: typeof AdminAccessUsersIdRouteWithChildren
}

const AdminAccessUsersRouteChildren: AdminAccessUsersRouteChildren = {
  AdminAccessUsersIdRoute: AdminAccessUsersIdRouteWithChildren,
}

const AdminAccessUsersRouteWithChildren =
  AdminAccessUsersRoute._addFileChildren(AdminAccessUsersRouteChildren)

interface AdminAccessRouteChildren {
  AdminAccessInvitesRoute: typeof AdminAccessInvitesRoute
  AdminAccessMcpRoute: typeof AdminAccessMcpRoute
  AdminAccessRolesRoute: typeof AdminAccessRolesRouteWithChildren
  AdminAccessUsersRoute: typeof AdminAccessUsersRouteWithChildren
}

const AdminAccessRouteChildren: AdminAccessRouteChildren = {
  AdminAccessInvitesRoute: AdminAccessInvitesRoute,
  AdminAccessMcpRoute: AdminAccessMcpRoute,
  AdminAccessRolesRoute: AdminAccessRolesRouteWithChildren,
  AdminAccessUsersRoute: AdminAccessUsersRouteWithChildren,
}

const AdminAccessRouteWithChildren = AdminAccessRoute._addFileChildren(
  AdminAccessRouteChildren,
)

interface AdminDomainsRouteChildren {
  AdminDomainsNewRoute: typeof AdminDomainsNewRoute
  AdminDomainsIdEditRoute: typeof AdminDomainsIdEditRoute
}

const AdminDomainsRouteChildren: AdminDomainsRouteChildren = {
  AdminDomainsNewRoute: AdminDomainsNewRoute,
  AdminDomainsIdEditRoute: AdminDomainsIdEditRoute,
}

const AdminDomainsRouteWithChildren = AdminDomainsRoute._addFileChildren(
  AdminDomainsRouteChildren,
)

interface AdminLinksIdRouteChildren {
  AdminLinksIdEditRoute: typeof AdminLinksIdEditRoute
}

const AdminLinksIdRouteChildren: AdminLinksIdRouteChildren = {
  AdminLinksIdEditRoute: AdminLinksIdEditRoute,
}

const AdminLinksIdRouteWithChildren = AdminLinksIdRoute._addFileChildren(
  AdminLinksIdRouteChildren,
)

interface AdminLinksRouteChildren {
  AdminLinksIdRoute: typeof AdminLinksIdRouteWithChildren
  AdminLinksNewRoute: typeof AdminLinksNewRoute
}

const AdminLinksRouteChildren: AdminLinksRouteChildren = {
  AdminLinksIdRoute: AdminLinksIdRouteWithChildren,
  AdminLinksNewRoute: AdminLinksNewRoute,
}

const AdminLinksRouteWithChildren = AdminLinksRoute._addFileChildren(
  AdminLinksRouteChildren,
)

interface AdminUserRouteChildren {
  AdminUserApiKeysRoute: typeof AdminUserApiKeysRoute
  AdminUserMcpRoute: typeof AdminUserMcpRoute
  AdminUserProfileRoute: typeof AdminUserProfileRoute
  AdminUserSessionsRoute: typeof AdminUserSessionsRoute
}

const AdminUserRouteChildren: AdminUserRouteChildren = {
  AdminUserApiKeysRoute: AdminUserApiKeysRoute,
  AdminUserMcpRoute: AdminUserMcpRoute,
  AdminUserProfileRoute: AdminUserProfileRoute,
  AdminUserSessionsRoute: AdminUserSessionsRoute,
}

const AdminUserRouteWithChildren = AdminUserRoute._addFileChildren(
  AdminUserRouteChildren,
)

interface AdminRouteChildren {
  AdminAccessRoute: typeof AdminAccessRouteWithChildren
  AdminDomainsRoute: typeof AdminDomainsRouteWithChildren
  AdminLinksRoute: typeof AdminLinksRouteWithChildren
  AdminUserRoute: typeof AdminUserRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminInviteTokenRoute: typeof AdminInviteTokenRoute
  AdminInvitesNewRoute: typeof AdminInvitesNewRoute
  AdminMcpConsentRoute: typeof AdminMcpConsentRoute
  AdminRolesNewRoute: typeof AdminRolesNewRoute
  AdminInvitesIdEditRoute: typeof AdminInvitesIdEditRoute
  AdminRolesIdEditRoute: typeof AdminRolesIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRoute: AdminAccessRouteWithChildren,
  AdminDomainsRoute: AdminDomainsRouteWithChildren,
  AdminLinksRoute: AdminLinksRouteWithChildren,
  AdminUserRoute: AdminUserRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminInviteTokenRoute: AdminInviteTokenRoute,
  AdminInvitesNewRoute: AdminInvitesNewRoute,
  AdminMcpConsentRoute: AdminMcpConsentRoute,
  AdminRolesNewRoute: AdminRolesNewRoute,
  AdminInvitesIdEditRoute: AdminInvitesIdEditRoute,
  AdminRolesIdEditRoute: AdminRolesIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
